# Generated by Django 4.1.7 on 2024-01-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("status", models.CharField(max_length=200)),
                ("score", models.FloatField()),
                ("disposable", models.BooleanField(blank=True, default=False)),
                ("domain", models.CharField(blank=True, max_length=200)),
                ("domain_score", models.FloatField(blank=True, null=True)),
                ("company", models.CharField(blank=True, max_length=200, null=True)),
                ("position", models.CharField(blank=True, max_length=200, null=True)),
                ("first_name", models.CharField(blank=True, max_length=200, null=True)),
                ("last_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "internal_status",
                    models.CharField(
                        blank=True, default="pending", max_length=200, null=True
                    ),
                ),
            ],
        ),
    ]
